### PR TITLE
update to v2.1.4

### PR DESCRIPTION
**Pull request by CKehl**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ocefpaf** [comment]
Can you incorporate the changes in https://github.com/conda-forge/parcels-feedstock/pull/53 here?

**Comment by erikvansebille** [comment]
> Can you incorporate the changes in #53 here?

We discussed and will not be incorporating in this version just yet. Because of the upcoming Ocean Sciences Meeting next week, we want a stable version. 

Perhaps in a next version, although we are now depending on qt so it won't be trivial

**Comment by ocefpaf** [comment]
> Perhaps in a next version, although we are now depending on qt so it won't be trivial

If you need matplotlib with `qt` then don't bother with #53. Just close it.

**Comment by CKehl** [comment]
k

**Pull request merged**
