### PR TITLE
Updating example_data download commands

### PR DESCRIPTION
**Pull request by erikvansebille**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by erikvansebille** [comment]
@conda-forge-admin, please rerender

**Comment by ocefpaf** [comment]
@erikvansebille, just to let you know, you can safely ignore the Azure failures for now.

**Comment by willirath** [comment]
See #37.

**Comment by willirath** [comment]
Looks very promising!

**Pull request merged**
