### PR TITLE
Adding pytest to parcels-feedstock recipe

### PR DESCRIPTION
**Pull request by erikvansebille**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Adding pytest to parcels-feedstock recipe

Since `pytest` is needed for the `example_peninsula.py` testcase that is mentioned in the Parcels installation instructions at step 5 of https://oceanparcels.org/#installing, it is good to add it as a requirement here too (it is already a requirement in https://github.com/OceanParcels/parcels/blob/master/environment_py3_linux.yml#L29).

### CODE REVIEW

**Comment by willirath** [comment]
I'm not sure it's good to add pytest as a hard dependency, as it _is_ possible to run Parcels without it. (My understanding of the dependencies listed in the recipes is that those are the required packages that are needed for the software to work at all.

Regarding the [example_peninsula.py](https://github.com/OceanParcels/parcels/blob/65e5d595ba4913d08c73b01eae3accc3a9bd57c1/parcels/examples/example_peninsula.py): The way it's used in [the parcels installation instructions](https://oceanparcels.org/#installing) would work without all the pytest aspects present in the file, as none of the tests is used when the `if __name__ == "__main__"` block is executed.

**Comment by erikvansebille** [comment]
Well, but there's the line [`import pytest`](
https://github.com/OceanParcels/parcels/blob/65e5d595ba4913d08c73b01eae3accc3a9bd57c1/parcels/examples/example_peninsula.py#L7) on line 7 of the example_peninsula.py file. I encountered a 'module not found error' when I did a fresh instal of parcels on a new system this afternoon; hence this PR.

**Comment by willirath** [comment]
I don't have any strong feelings about this, though. The parcels package already is kind of a meta package with results in a complete (or almost complete) environment anyway. So there would probably result no actual harm from including `pytest` as a runtime dependency.

**Review by willirath — APPROVED** [review]

**Comment by willirath** [comment]
> I don't have any strong feelings about this, though. The parcels package already is kind of a meta package which results in a complete (or almost complete) environment anyway. So there would probably result no actual harm from including `pytest` as a runtime dependency.

So let's merge then. :)

**Pull request merged**
